import { DataType } from "@/app/mint/page";
import React, { Component, Dispatch, SetStateAction, useState } from "react";
import Select, { SingleValue } from "react-select";

const sampleData = [
  { building_name: "Willow Heights Apartments" },
  { building_name: "Cedar Grove Condominiums" },
  { building_name: "Maplewood Towers" },
  { building_name: "Oakwood Manor" },
  { building_name: "Birchwood Place" },
  { building_name: "Pinecrest Residences" },
  { building_name: "Elmwood Gardens" },
  { building_name: "Magnolia Court Apartments" },
  { building_name: "Sycamore Ridge Estates" },
  { building_name: "Rosewood Plaza Condos" },
  { building_name: "Aspen Meadows Towers" },
  { building_name: "Cypress Pointe Villas" },
  { building_name: "Juniper Ridge Apartments" },
  { building_name: "Cherry Blossom Heights" },
  { building_name: "Birchwood Terrace Condos" },
  { building_name: "Willow Creek Residences" },
  { building_name: "Cedar Ridge Estates" },
  { building_name: "Maplewood Grove Apartments" },
  { building_name: "Oakwood Park Condos" },
  { building_name: "Birchwood Meadows Towers" },
  { building_name: "Pineview Condominiums" },
  { building_name: "Elmwood Square Apartments" },
  { building_name: "Magnolia Gardens Residences" },
  { building_name: "Sycamore Hills Towers" },
  { building_name: "Rosewood Manor Condos" },
  { building_name: "Aspen Ridge Estates" },
  { building_name: "Cypress Grove Residences" },
  { building_name: "Juniper Court Apartments" },
  { building_name: "Cherrywood Place Condos" },
  { building_name: "Birchwood Village Residences" },
  { building_name: "Willowbrook Towers" },
  { building_name: "Cedarwood Terrace Apartments" },
  { building_name: "Maple Heights Condos" },
  { building_name: "Oakwood Springs Residences" },
  { building_name: "Birchwood Place Apartments" },
  { building_name: "Pinehurst Estates Towers" },
  { building_name: "Elmwood Ridge Condos" },
  { building_name: "Magnolia Park Residences" },
  { building_name: "Sycamore Court Apartments" },
  { building_name: "Rosewood Residences Towers" },
  { building_name: "Aspenwood Villas" },
  { building_name: "Cypress Creek Condominiums" },
  { building_name: "Juniper Gardens Residences" },
  { building_name: "Cherrywood Heights Towers" },
  { building_name: "Birchwood Lane Apartments" },
  { building_name: "Willowcrest Towers" },
  { building_name: "Cedar Grove Apartments" },
  { building_name: "Maplewood Meadows Condos" },
  { building_name: "Oakwood Place Residences" },
  { building_name: "Birchwood Grove Towers" },
  { building_name: "Pineview Terrace Apartments" },
  { building_name: "Elmwood Manor Condos" },
  { building_name: "Magnolia Square Residences" },
  { building_name: "Sycamore Ridge Towers" },
  { building_name: "Rosewood Gardens Apartments" },
  { building_name: "Aspen Court Condos" },
  { building_name: "Cypress Pointe Residences" },
  { building_name: "Juniper Springs Towers" },
  { building_name: "Cherry Blossom Condos" },
  { building_name: "Birchwood Ridge Residences" },
  { building_name: "Willow Creek Estates Towers" },
  { building_name: "Cedarwood Gardens Apartments" },
  { building_name: "Maplewood Plaza Condos" },
  { building_name: "Oakwood Village Residences" },
  { building_name: "Birchwood Park Towers" },
  { building_name: "Pinecrest Condominiums" },
  { building_name: "Elmwood Place Apartments" },
  { building_name: "Magnolia Heights Towers" },
  { building_name: "Sycamore Grove Residences" },
  { building_name: "Rosewood Terrace Condos" },
  { building_name: "Aspen Meadows Apartments" },
  { building_name: "Cypress Ridge Estates" },
  { building_name: "Juniper Court Condos" },
  { building_name: "Cherrywood Meadows Residences" },
  { building_name: "Birchwood Square Towers" },
  { building_name: "Cedar Ridge Condos" },
  { building_name: "Maplewood Gardens Residences" },
  { building_name: "Oakwood Hills Towers" },
  { building_name: "Birchwood Residences" },
  { building_name: "Pinehurst Place Condos" },
  { building_name: "Elmwood Village Towers" },
  { building_name: "Magnolia Springs Residences" },
  { building_name: "Sycamore Place Condos" },
  { building_name: "Rosewood Ridge Towers" },
  { building_name: "Aspen Park Apartments" },
  { building_name: "Cypress Court Condos" },
  { building_name: "Juniper Grove Residences" },
  { building_name: "Cherrywood Manor Towers" },
  { building_name: "Birchwood Court Apartments" },
  { building_name: "Willowcrest Residences" },
  { building_name: "Cedar Grove Villas" },
  { building_name: "Maplewood Condominiums" },
  { building_name: "Oakwood Terrace Apartments" },
  { building_name: "Birchwood Springs Condos" },
  { building_name: "Pineview Square Residences" },
  { building_name: "Elmwood Heights Towers" },
  { building_name: "Magnolia Ridge Apartments" },
  { building_name: "Sycamore Village Condos" },
  { building_name: "Rosewood Park Residences" },
  { building_name: "Aspenwood Towers" },
  { building_name: "Cypress Creek Apartments" },
  { building_name: "Juniper Gardens Condos" },
  { building_name: "Birchwood Lane Residences" },
  { building_name: "Willowcrest Apartments" },
  { building_name: "Cedarwood Grove Condos" },
  { building_name: "Maple Heights Towers" },
  { building_name: "Birchwood Grove Condos" },
  { building_name: "Pineview Terrace Towers" },
  { building_name: "Elmwood Manor Apartments" },
  { building_name: "Magnolia Square Condos" },
  { building_name: "Rosewood Gardens Residences" },
  { building_name: "Cypress Pointe Towers" },
  { building_name: "Juniper Springs Apartments" },
  { building_name: "Birchwood Ridge Towers" },
  { building_name: "Cedarwood Square Condos" },
  { building_name: "Maplewood Meadows Towers" },
  { building_name: "Oakwood Park Apartments" },
  { building_name: "Birchwood Place Condos" },
  { building_name: "Pinecrest Estates Towers" },
  { building_name: "Elmwood Ridge Residences" },
  { building_name: "Magnolia Park Condos" },
  { building_name: "Sycamore Court Towers" },
  { building_name: "Rosewood Residences Apartments" },
  { building_name: "Maplewood Grove Condos" },
  { building_name: "Cedarwood Heights Residences" },
  { building_name: "Birchwood Crest Apartments" },
  { building_name: "Magnolia Springs Condos" },
  { building_name: "Elmwood Ridge Estates" },
  { building_name: "Sycamore Grove Apartments" },
  { building_name: "Pineview Terrace Residences" },
  { building_name: "Aspen Court Towers" },
  { building_name: "Cherrywood Plaza Condominiums" },
  { building_name: "Maplewood Park Apartments" },
  { building_name: "Oakwood Manor Towers" },
  { building_name: "Birchwood Ridge Estates" },
  { building_name: "Cedar Grove Condos" },
  { building_name: "Rosewood Residences" },
  { building_name: "Willow Heights Condominiums" },
  { building_name: "Magnolia Court Residences" },
  { building_name: "Sycamore Park Towers" },
  { building_name: "Pinecrest Place Apartments" },
  { building_name: "Aspen Meadows Condos" },
  { building_name: "Cherry Blossom Heights Residences" },
  { building_name: "Juniper Ridge Towers" },
  { building_name: "Maplewood Gardens Apartments" },
  { building_name: "Oakwood Plaza Condos" },
  { building_name: "Birchwood Meadows Residences" },
  { building_name: "Cedarwood Manor Towers" },
  { building_name: "Rosewood Park Apartments" },
  { building_name: "Cypress Grove Condos" },
  { building_name: "Elmwood Terrace Residences" },
  { building_name: "Willow Ridge Towers" },
  { building_name: "Magnolia Oaks Apartments" },
  { building_name: "Sycamore Lane Condominiums" },
  { building_name: "Pineview Heights Residences" },
  { building_name: "Aspen Grove Towers" },
  { building_name: "Cherrywood Springs Apartments" },
  { building_name: "Maplewood Ridge Residences" },
  { building_name: "Oakwood Pointe Towers" },
  { building_name: "Birchwood Village Apartments" },
  { building_name: "Cedarwood Springs Condominiums" },
  { building_name: "Rosewood Square Residences" },
  { building_name: "Cypress Hills Towers" },
  { building_name: "Elmwood Grove Apartments" },
  { building_name: "Willowbrook Condos" },
  { building_name: "Magnolia Lane Residences" },
  { building_name: "Sycamore Springs Towers" },
  { building_name: "Pinecrest Meadows Apartments" },
  { building_name: "Aspen Park Condominiums" },
  { building_name: "Cherrywood Grove Residences" },
  { building_name: "Juniper Terrace Towers" },
  { building_name: "Maplewood Manor Apartments" },
  { building_name: "Oakwood Ridge Condos" },
  { building_name: "Birchwood Court Residences" },
  { building_name: "Cedar Grove Towers" },
  { building_name: "Rosewood Terrace Apartments" },
  { building_name: "Cypress Ridge Condominiums" },
  { building_name: "Elmwood Place Residences" },
  { building_name: "Magnolia Hills Apartments" },
  { building_name: "Sycamore Court Condos" },
  { building_name: "Pineview Grove Residences" },
  { building_name: "Aspen Crest Towers" },
  { building_name: "Cherrywood Manor Apartments" },
  { building_name: "Juniper Park Condos" },
  { building_name: "Maplewood Springs Residences" },
  { building_name: "Oakwood Lane Towers" },
  { building_name: "Birchwood Ridge Condominiums" },
  { building_name: "Rosewood Meadows Towers" },
  { building_name: "Cypress Pointe Apartments" },
  { building_name: "Elmwood Gardens Condos" },
  { building_name: "Willow Heights Residences" },
  { building_name: "Magnolia Court Towers" },
  { building_name: "Sycamore Park Apartments" },
  { building_name: "Pinecrest Place Condominiums" },
  { building_name: "Aspen Meadows Residences" },
  { building_name: "Cherry Blossom Heights Towers" },
  { building_name: "Maplewood Gardens Condos" },
  { building_name: "Oakwood Plaza Residences" },
  { building_name: "Cedarwood Manor Apartments" },
  { building_name: "Rosewood Park Condos" },
  { building_name: "Elmwood Terrace Towers" },
  { building_name: "Willow Ridge Apartments" },
  { building_name: "Magnolia Oaks Condominiums" },
  { building_name: "Sycamore Lane Residences" },
  { building_name: "Pineview Heights Towers" },
  { building_name: "Aspen Grove Apartments" },
  { building_name: "Cherrywood Springs Condos" },
  { building_name: "Juniper Court Residences" },
  { building_name: "Maplewood Ridge Towers" },
  { building_name: "Oakwood Pointe Apartments" },
  { building_name: "Birchwood Village Condos" },
  { building_name: "Cedarwood Springs Residences" },
  { building_name: "Rosewood Square Towers" },
  { building_name: "Cypress Hills Apartme" },
  { building_name: " Astor Plaza" },
  { building_name: "1 Bryant Park" },
  { building_name: "1聽Carnegie Hill" },
  { building_name: "1 Central Park" },
  { building_name: "1 Dag Hammarskjold Plaza" },
  { building_name: "1 Fifth Avenue" },
  { building_name: "1 Financial Square" },
  { building_name: "1 Grand Army Plaza" },
  { building_name: "1 Liberty Plaza" },
  { building_name: "1 N.Y.Plaza" },
  { building_name: "1 Penn Plaza" },
  { building_name: "1 Rockefeller Plaza" },
  { building_name: "1 Seaport Plaza" },
  { building_name: "1 Times Square" },
  { building_name: "1 Union Square South" },
  { building_name: "1 Wall Street" },
  { building_name: "1 World Financial Center" },
  { building_name: "1 World Trade Center" },
  { building_name: "1 Word Trade Center" },
  { building_name: "1 Worldwide Plaza" },
  { building_name: "10 Columbus Circle" },
  { building_name: "10 E 40th Street" },
  { building_name: "100 Park Avenue" },
  { building_name: "100 U.N.Plaza" },
  { building_name: "100 William Street" },
  { building_name: "1001 Fifth Avenue" },
  { building_name: "101 Park Avenue" },
  { building_name: "101 Warren St" },
  { building_name: "101 West End Avenue" },
  { building_name: "11 Times" },
  { building_name: "110 East 42nd Street" },
  { building_name: "1133 Sixth Avenue" },
  { building_name: "1166 Sixth Avenue" },
  { building_name: "12 Metrotech" },
  { building_name: "120 Wall Street" },
  { building_name: "127 John Street" },
  { building_name: "1270 Sixth Avenue" },
  { building_name: "130 Liberty Street" },
  { building_name: "135 East 57th Street" },
  { building_name: "15 Columbus Circle" },
  { building_name: "15 William Street" },
  { building_name: "1515 Broadway" },
  { building_name: "1585 Broadway" },
  { building_name: "165 Charles Street" },
  { building_name: "17 State Street" },
  { building_name: "173 Perry Street" },
  { building_name: "1739 Broadway" },
  { building_name: "175 East 96th Street" },
  { building_name: "176 Perry Street" },
  { building_name: "2 Broadway" },
  { building_name: "2 Columbus Circle" },
  { building_name: "2 Dag Hammarskjold" },
  { building_name: "2 N.Y.Plaza" },
  { building_name: "2 Penn Plaza" },
  { building_name: "2 Times" },
  { building_name: "2 World Financial Center" },
  { building_name: "2 World Trade Center" },
  { building_name: "20 River Terrace" },
  { building_name: "20 Exchange Place" },
  { building_name: "20 Times" },
  { building_name: "200 Water Street" },
  { building_name: "211 North End Avenue" },
  { building_name: "211 West 56th Street" },
  { building_name: "22 River Terrace" },
  { building_name: "230 West 56th Street" },
  { building_name: "240 Riverside Boulevard at Trump Place" },
  { building_name: "275 Madison Avenue" },
  { building_name: "3 Times Square" },
  { building_name: "3 World Financial Center" },
  { building_name: "30 Broad Street" },
  { building_name: "30 Hudson Street" },
  { building_name: "33 Vestry Street" },
  { building_name: "300 Madison Avenue" },
  { building_name: "325 Fifth Avenue" },
  { building_name: "33 Maiden Lane" },
  { building_name: "34 River Terrace" },
  { building_name: "320 West 38th Street" },
  { building_name: "343 West 42nd Street" },
  { building_name: "345 Park Avenue" },
  { building_name: "350 West 50th Street" },
  { building_name: "383 Madison Avenue" },
  { building_name: "4 N.Y.Plaza" },
  { building_name: "4 Times Square" },
  { building_name: "4 World Financial Center" },
  { building_name: "40 Wall Street" },
  { building_name: "41 River Terrace" },
  { building_name: "402 East 67th Street" },
  { building_name: "425 Fifth Avenue" },
  { building_name: "48 Wall Street" },
  { building_name: "497 Greenwich Street" },
  { building_name: "5 Times Square" },
  { building_name: "500 Fifth Avenue" },
  { building_name: "50 East 42nd Street" },
  { building_name: "505 Fifth Avenue" },
  { building_name: "505 Greenwich Street" },
  { building_name: "520 Madison Avenue" },
  { building_name: "55 Water Street" },
  { building_name: "59 Maiden Lane" },
  { building_name: "599 Lexington Avenue" },
  { building_name: "60 Wall Street" },
  { building_name: "600 West 42nd Street" },
  { building_name: "601 Lexington Avenue" },
  { building_name: "63 Wall Street" },
  { building_name: "666 Fifth Avenue" },
  { building_name: "7 Times Square" },
  { building_name: "7 World Trade Center" },
  { building_name: "70 Little West Street" },
  { building_name: "70 Pine Street" },
  { building_name: "712 Fifth Avenue" },
  { building_name: "731 Lexington" },
  { building_name: "745 Seventh Avenue" },
  { building_name: "750 Seventh Avenue" },
  { building_name: "77 Water Street" },
  { building_name: "777 Third Avenue" },
  { building_name: "80 South Street" },
  { building_name: "85 Broad Street" },
  { building_name: "845 UN Plaza" },
  { building_name: "860 - 870 U.N.Plaza" },
  { building_name: "88 Pine Street" },
  { building_name: "885 Third Avenue 鈥Lipstick" },
  { building_name: "9 W 57th Street" },
  { building_name: "90 West Street" },
  { building_name: "Adams Building" },
  { building_name: "American Brands Building" },
  { building_name: "American International Building" },
  { building_name: "American Radiator Building" },
  { building_name: "American Standard Building" },
  { building_name: "American Tract Society Building" },
  { building_name: "The Andover" },
  { building_name: "Annenberg Building" },
  { building_name: "AOL Time Warner Center" },
  { building_name: "Arthur A.Schomburg Plaza" },
  { building_name: "Astor Place" },
  { building_name: "AT & T Building" },
  { building_name: "AT & T Long Lines Building" },
  { building_name: "Avalon Riverview" },
  { building_name: "The Bamford" },
  { building_name: "Bankers Trust Co.Building" },
  { building_name: "Bankers Trust Plaza" },
  { building_name: "Bank of America Tower" },
  { building_name: "Bank of Manhattan Building" },
  { building_name: "Bank of New York Building(48 Wall St.)" },
  { building_name: "Bank of New York Building II(1 Wall St.)" },
  { building_name: "The Barclay" },
  { building_name: "Barclay Tower" },
  { building_name: "Barclay - Vesey Building" },
  { building_name: "Bayard - Condict Building" },
  { building_name: "Beekman Tower" },
  { building_name: "The Belmont" },
  { building_name: "Beresford Apartments" },
  { building_name: "Bertelsmann Building" },
  { building_name: "Bloomberg Tower" },
  { building_name: "Bowery Savings Bank" },
  { building_name: "Briar Hill" },
  { building_name: "The Bristol" },
  { building_name: "The Brittany" },
  { building_name: "Bush Tower" },
  { building_name: "The Caldwell" },
  { building_name: "The Cambridge" },
  { building_name: "Canada House" },
  { building_name: "Candler Building" },
  { building_name: "Carnegie Hall Tower" },
  { building_name: "Carnegie Mews" },
  { building_name: "CBS Building" },
  { building_name: "Celanese Building" },
  { building_name: "Central Park Place" },
  { building_name: "Century Apartments" },
  { building_name: "Chanin Building" },
  { building_name: "Chase Manhattan Bank" },
  { building_name: "Chatham Towers" },
  { building_name: "Chemical Bank Building" },
  { building_name: "Chrysler Building" },
  { building_name: "Chrysler Building East" },
  { building_name: "CIBC World Markets" },
  { building_name: "Citigroup Center" },
  { building_name: "Cities Service Building" },
  { building_name: "City Bank Farmers Trust Co.Building" },
  { building_name: "Citylights" },
  { building_name: "Cityspire" },
  { building_name: "Columbus Centre" },
  { building_name: "Cond茅 Nast Building" },
  { building_name: "Confucius Plaza" },
  { building_name: "Continental Center" },
  { building_name: "Corning Glass Building" },
  { building_name: "Crown Building" },
  { building_name: "Dag Hammarskjold Tower" },
  { building_name: "Daily News Building" },
  { building_name: "Deutsche Bank Building" },
  { building_name: "Doubletree Guest Suites" },
  { building_name: "Downtown Athletic Club" },
  { building_name: "Durst Tower" },
  { building_name: "Eldorado Apartments" },
  { building_name: "Empire State Building" },
  { building_name: "Equitable Building I" },
  { building_name: "Equitable Building II" },
  { building_name: "Equitable Center" },
  { building_name: "Ernst & Young National Headquarters" },
  { building_name: "Essex House" },
  { building_name: "Exxon Building" },
  { building_name: "The Fairmont" },
  { building_name: "Flatiron Building" },
  { building_name: "Four Seasons Hotel" },
  { building_name: "Freedom Tower" },
  { building_name: "Fuller Building" },
  { building_name: "Galleria" },
  { building_name: "GE Building" },
  { building_name: "General Electric Tower" },
  { building_name: "General Motors Building" },
  { building_name: "Goldman Sachs Tower" },
  { building_name: "Grace Building" },
  { building_name: "The Grand Tier" },
  { building_name: "Group Health Insurance Building" },
  { building_name: "Gulf & Western Building" },
  { building_name: "The Hamilton" },
  { building_name: "Hampton Court" },
  { building_name: "Hearst Magazine Building" },
  { building_name: "Helena" },
  { building_name: "Helmsley Building" },
  { building_name: "Helmsley Palace Hotel" },
  { building_name: "Heckscher Building" },
  { building_name: "Home Insurance Company Building" },
  { building_name: "IBM Building" },
  { building_name: "InterActiveCorp Headquarters" },
  { building_name: "Interchem Building" },
  { building_name: "International Building" },
  { building_name: "Irving Trust Co.Building" },
  { building_name: "Jacob Ruppert Brewery Project" },
  { building_name: "Javits Federal Office Building" },
  { building_name: "J.P.Morgan Bank Headquarters" },
  { building_name: "Kent Building" },
  { building_name: "Lehman Brothers Building" },
  { building_name: "Lefcourt Colonial Building" },
  { building_name: "Lever Building" },
  { building_name: "Liberty Plaza" },
  { building_name: "Lincoln Building" },
  { building_name: "Lipstick Building" },
  { building_name: "The Lucerne" },
  { building_name: "LVMH Tower" },
  { building_name: "Majestic Apartments" },
  { building_name: "Manufacturers Hanover Trust Building" },
  { building_name: "Marc" },
  { building_name: "Marine Midland Bank" },
  { building_name: "The Marlowe" },
  { building_name: "Marriott East Side Hotel" },
  { building_name: "Marriott Marquis Hotel" },
  { building_name: "Marriott Brooklyn" },
  { building_name: "McGraw - Hill Building I(330 W 42nd St.)" },
  { building_name: "McGraw - Hill Building II(1221 Sixth Ave.)" },
  { building_name: "Met Life Building" },
  { building_name: "Metropolitan Life Insurance Co.Tower" },
  { building_name: "Metropolitan Tower" },
  { building_name: "Milan" },
  { building_name: "Millennium Broadway Hotel" },
  { building_name: "Millennium Hilton Hotel" },
  { building_name: "Milstein" },
  { building_name: "Mobil Building" },
  { building_name: "The Monterey" },
  { building_name: "MONY Tower" },
  { building_name: "Morgan Stanley Building(1585 Broadway)" },
  { building_name: "Morgan Stanley Dean Witter Plaza" },
  { building_name: "Morton Square" },
  { building_name: "Municipal Building" },
  { building_name: "Museum Tower" },
  { building_name: "National Westminster Bank USA" },
  { building_name: "Nelson Tower" },
  { building_name: "New York Central Building" },
  { building_name: "New Yorker Hotel" },
  { building_name: "New York Hilton Hotel" },
  { building_name: "New York Merchandise Mart" },
  { building_name: "New York Palace Hotel" },
  { building_name: "New York Times Tower" },
  { building_name: "New York World Building" },
  { building_name: "N.Y.Life Insurance Co.Building" },
  { building_name: "N.Y.Telephone Co.Building(Midtown)" },
  { building_name: "N.Y.Telephone Co.Building(Murray Hill)" },
  { building_name: "N.Y.Telephone Co.Switching Station(Downtown)" },
  { building_name: "N.Y.Telephone Co.Switching Station(W.Midtown)" },
  { building_name: "Olympic Tower" },
  { building_name: "On Prospect Park" },
  { building_name: "One Bryant Park" },
  { building_name: "One Carnegie Hill" },
  { building_name: "One Dag Hammarskjold Plaza" },
  { building_name: "One Fifth Avenue" },
  { building_name: "One Penn Plaza" },
  { building_name: "One Union Square South" },
  { building_name: "Orion" },
  { building_name: "Pan Am Building" },
  { building_name: "Panhellenic Hotel" },
  { building_name: "Paramount Building" },
  { building_name: "Paramount Plaza" },
  { building_name: "Paramount Tower" },
  { building_name: "Park Avenue Place" },
  { building_name: "Park Avenue Plaza" },
  { building_name: "Park Imperial" },
  { building_name: "Park Lane Hotel" },
  { building_name: "Park Row Building" },
  { building_name: "The Pavilion" },
  { building_name: "Pennmark" },
  { building_name: "Perry West" },
  { building_name: "Philip Morris Inc.Building" },
  { building_name: "Piaget Building" },
  { building_name: "Pierre" },
  { building_name: "Random House Building" },
  { building_name: "RCA Building" },
  { building_name: "Realty Building" },
  { building_name: "The Regent" },
  { building_name: "Reuters Building" },
  { building_name: "Ritz Tower" },
  { building_name: "RKO Building" },
  { building_name: "San Remo Apartments" },
  { building_name: "Seagram Building" },
  { building_name: "Seward Park Houses Extension" },
  { building_name: "Sheraton Centre" },
  { building_name: "Silver Towers" },
  { building_name: "Singer Tower" },
  { building_name: "Socony - Mobil Building" },
  { building_name: "Solaire" },
  { building_name: "Solow Building" },
  { building_name: "The Somerset" },
  { building_name: "Sony Building" },
  { building_name: "South Park Tower" },
  { building_name: "Standard Oil Building" },
  { building_name: "The Stratford" },
  { building_name: "Taino Towers" },
  { building_name: "Thames Twins" },
  { building_name: "Time and Life Building" },
  { building_name: "Time - Life Building" },
  { building_name: "Time Warner Center" },
  { building_name: "Times Square Tower" },
  { building_name: "Times Tower" },
  { building_name: "Time Warner Building" },
  { building_name: "Tishman Building" },
  { building_name: "Tribeca Bridge Tower" },
  { building_name: "Tribeca Park" },
  { building_name: "Tribeca Pointe" },
  { building_name: "Trinity Building" },
  { building_name: "Trump Tower" },
  { building_name: "Trump International Hotel & Tower" },
  { building_name: "Trump" },
  { building_name: "Trump World Tower" },
  { building_name: "(1 & 2) U.N.Plaza 鈥Park Hyatt Hotel" },
  { building_name: "Union Carbide Building" },
  { building_name: "United Nations Secretariat" },
  { building_name: "Universal Pictures Building" },
  { building_name: "University Plaza" },
  { building_name: "Uris Building" },
  { building_name: "U.S.Courthouse" },
  { building_name: "U.S.Plywood Building" },
  { building_name: "U.S.Steel Building" },
  { building_name: "Verdesian" },
  { building_name: "Victory" },
  { building_name: "Visionaire" },
  { building_name: "Waldorf Astoria Hotel" },
  { building_name: "Waterside" },
  { building_name: "The Westport" },
  { building_name: "Western Union Building" },
  { building_name: "The Whitehall Building" },
  { building_name: "Whitehall Building Annex" },
  { building_name: "The Windermere" },
  { building_name: "Woolworth Building" },
  { building_name: "World Trade Center" },
  { building_name: "World Trade Center Tower #1" },
  { building_name: "W.R.Grace Building" },
  { building_name: "Carnegie 57" },
  { building_name: "One Madison Park" },
  { building_name: "Cassa NY聽at 70 West 45th Street" },
  { building_name: "One World Tade Center a.k.a.Freedom Tower" },
  { building_name: "100 Eleventh Avenue聽a.k.a.Jean Nouvel鈥s Vision Machine" },
  {
    building_name: "130 Liberty Street聽鈥Demolition 鈥Deutsche Bank Building",
  },
  { building_name: "150 Greenwich Street聽鈥World Trade Center聽Tower #4" },
  { building_name: "400 Fifth Avenue聽鈥Setai Hotel and Condo" },
  { building_name: "8 Spruce Street a.k.a.Beekman Street Tower" },
  { building_name: "99 Church Street聽鈥Four Seasons Hotel & Tower" },
  { building_name: "Clinton Park聽鈥770 11th Ave @53rd & 54th" },
  { building_name: "Fiterman Hall聽鈥30 West Broadway" },
  { building_name: "Fulton Street Transit Center" },
  { building_name: "International Gem Tower聽at 55 West 46th Street" },
  { building_name: "Lincoln Center Redesign" },
  { building_name: "Metal Shutter Houses聽at 524 West 19th Street" },
  { building_name: "Times Square Plaza a.k.a. 11 Times Square" },
  { building_name: "World Trade Center Memorial" },
  { building_name: "World Trade Center Transportation Hub" },
  { building_name: "One World Trade Center a.k.a.Freedom Tower" },
  { building_name: "99 Church Street 鈥Four Seasons Hotel & Tower" },
  { building_name: "400 Fifth Avenue" },
  { building_name: "W New York Downtown聽a.k.a.聽123 Washington Street" },
  { building_name: "Eventi聽at 839 Sixth Avenue" },
  { building_name: "785 Eighth Avenue" },
  { building_name: "111 Lawrence Street(Downtown Brooklyn)" },
  { building_name: "International Gem聽Tower at 55 West 46th Street" },
  { building_name: "505 West 37th Street 鈥East Tower" },
  { building_name: "150 Amsterdam Avenue" },
  { building_name: "Trump SoHo" },
  { building_name: "99 Washington Street a.k.a.Radisson Financial Hotel" },
  { building_name: "311 West 39th Street" },
  { building_name: "80 Dekalb Avenue(Brooklyn)" },
  { building_name: "Toren" },
  { building_name: "Avalon Fort Greene(Brooklyn)" },
  { building_name: "510 Madison" },
  { building_name: "200 Greenwich Street聽鈥World Trade Center Tower #2" },
  { building_name: "175 Greenwich Street聽鈥World Trade Center Tower #3" },
  { building_name: "Tower Verre at 53 West 53rd Street" },
  { building_name: "One Manhattan West" },
  { building_name: "15 Penn Plaza" },
  { building_name: "World Product Centre" },
  { building_name: "The Girasole" },
  { building_name: "City Tech Tower(Downtown Brooklyn)" },
  { building_name: "155 West 57th Street" },
  { building_name: "One Madison Avenue" },
  { building_name: "Two Manhattan West" },
  { building_name: "20 Times Square" },
  { building_name: "56 Leonard Street" },
  { building_name: "260 Twelfth Avenue" },
  { building_name: "700聽First Avenue 鈥撀Con Ed聽Redevelopment Site" },
  { building_name: "360 Tenth Avenue" },
  { building_name: "WTC Tower #5" },
  { building_name: "50 West Street" },
  { building_name: "610 Lexington Avenue" },
  { building_name: "250 East 57th Street" },
  {
    building_name: "700聽First Avenue 鈥Tower 1 鈥撀Con Ed聽Redevelopment Sit",
  },
  { building_name: "Nobu Hotel & Residences" },
  { building_name: "20 East 53rd Street" },
  { building_name: "160 West 62nd Street" },
  { building_name: "Atlantic Yards聽鈥Miss Brooklyn鈥Downtown Brooklyn)" },
  { building_name: "605 West 42nd Street" },
  { building_name: "440 West 42nd Street" },
  { building_name: "Queens Street Apartments(LIC)" },
  { building_name: "Silver Cup West 鈥Tower聽1 鈥Hunters Point)" },
  { building_name: "135 West 45th Street" },
  {
    building_name: "4 East 102nd Street 鈥Mount Sinai Center for Science and ",
  },
  { building_name: "Silver Cup West 鈥Tower 2 鈥Hunters Point)" },
  { building_name: "388 Bridge Street(Downtown Brooklyn)" },
  { building_name: "823 United Nations Plaza" },
  { building_name: "Silver Cup West 鈥Tower聽3 鈥Hunters Point)" },
  { building_name: "Atlantic Yards聽鈥撀Building 4(Downtown Brooklyn)" },
  { building_name: "303 East 51st Street" },
  { building_name: "Seaport Tower" },
  { building_name: "828 Washington Street" },
  { building_name: "29 Flatbush Avenue(Downtown Brooklyn)" },
  { building_name: "176 Madison Avenue" },
  { building_name: "U.N.Headquarters Expansion" },
  { building_name: "400 Park Avenue South" },
  { building_name: "855 Sixth Avenue" },
  { building_name: "Atlantic Yards聽鈥撀Building聽7(Downtown Brooklyn)" },
  { building_name: "309 Fifth Avenue" },
  { building_name: "158 Madison Avenue" },
  { building_name: "Brooklyn Arts Tower(Downtown Brooklyn)" },
  { building_name: "577 Ninth Avenue" },
  { building_name: "220 Central Park South" },
  { building_name: "Two Sutton Place North" },
  { building_name: "162聽Myrtle Avenue(Brooklyn)" },
  { building_name: "Oro 鈥Tower II 鈥313 Gold Street" },
  { building_name: "85 Flatbush Avenue Extension" },
  { building_name: "100 Eleventh Avenue a.k.a.Jean Nouvel鈥s Vision Machine" },
  { building_name: "8 Union Square West" },
  { building_name: "Atlantic Terminal Transit Hub(Brooklyn)" },
  { building_name: "Brooklyn Bridge Park 鈥Phase I" },
  { building_name: "Cooper - Hewitt Museum Expansion" },
  { building_name: "East River Science Park" },
  { building_name: "The Edge I(Williamsburg, Brooklyn)" },
  { building_name: "John Jay College of Criminal Justice Expansion" },
  { building_name: "The Laurel at 400 East 67th Street" },
  { building_name: "Metal Shutter Houses at 524 West 19th Street" },
  { building_name: "Mount Sinai Center for Science and Medicine" },
  { building_name: "Sheraton Downtown Brooklyn Hotel" },
  { building_name: "Aloft Downtown Brooklyn Hotel" },
  { building_name: "Superior Ink Condominiums 鈥469 West Street" },
  { building_name: "Toren(Downtown Brooklyn)" },
  { building_name: "Trump SOHO" },
  { building_name: "Two Northside Piers(Brooklyn)" },
  { building_name: "200 Eleventh" },
  { building_name: "One Bryant Park(Bank of America Tower)" },
  { building_name: "124 East 12th Street" },
  { building_name: "255 East 74th Street" },
  { building_name: "290 Mulberry Street" },
  { building_name: "455 West 37th Street" },
  { building_name: "63 West 35th Street" },
  { building_name: "CitiField(Mets Stadium)" },
  { building_name: "Columbus Village at 808 Columbus Avenue" },
  { building_name: "Cooper Union New Academic Building" },
  { building_name: "Fifth on the Park" },
  { building_name: "Floating Ferry Terminal at Battery Park City" },
  { building_name: "Goldman Sachs Headquarters" },
  { building_name: "High Line Park 鈥Phase I" },
  { building_name: "Linden 78 at 230 West 78th Street" },
  { building_name: "South Ferry Terminal" },
  { building_name: "Standard Hotel" },
  { building_name: "Visionaire聽at 70 West Little 12th Street" },
  { building_name: "New Yankee Stadium" },
  { building_name: "West 57th Street by Hilton Club" },
  { building_name: "One Northside Piers(Williamsburg, Brooklyn)" },
  { building_name: "One York" },
  { building_name: "15 Central Park West" },
  { building_name: "101 Warren Street" },
  { building_name: "1330 First Avenue" },
  { building_name: "188 Ludlow Street" },
  { building_name: "2 Columbus Circle聽鈥Museum of Arts and Design" },
  { building_name: "200 West End Ave" },
  { building_name: "240 Park Avenue South" },
  { building_name: "25 Bond Street" },
  { building_name: "30 West 18th Street" },
  { building_name: "47 East 34th Street" },
  { building_name: "48 Bond Street" },
  { building_name: "The Caledonia at 450 West 17th Street" },
  { building_name: "Chatham 44 鈥464 West 44th Steet" },
  { building_name: "Chelsea Modern at 447 West 18th Street" },
  { building_name: "Chelsea Stratus聽at 101 West 24th Street" },
  { building_name: "Cooper Square Hotel at 25 Cooper Square" },
  { building_name: "East Coast Tower II(Queens West)" },
  { building_name: "The Element at 555 West 59th Street" },
  {
    building_name: "Hampton Inn / Candlewood Suites / Holiday Inn Express at ",
  },
  { building_name: "Oculus at 50 West 15th Street" },
  { building_name: "On Prospect Park(Brooklyn)" },
  { building_name: "Oro at 306 Gold Street(Downtown Brooklyn)" },
  { building_name: "Platinum聽at 247 West 46th Street" },
  { building_name: "Riverhouse聽at 1 River Terrace" },
  { building_name: "Rushmore聽at 80 Riverside Boulevard" },
  { building_name: "Sky House聽at 11 East 29th Street" },
  { building_name: "New TKTS聽Center in Times Square" },
  { building_name: "Twenty9th Park Madison" },
  { building_name: "William Beaver House 鈥15 William Street" },
  { building_name: "1 East 35th Street" },
  { building_name: "One Ten 3rd 鈥110 Third Ave" },
  { building_name: "10 West End Avenue" },
  { building_name: "200 Chambers Street" },
  { building_name: "ThreeTen East 53聽at 310 East 53rd Street" },
  { building_name: "40 Bond Street" },
  { building_name: "40 Mercer" },
  { building_name: "88 Leonard Street" },
  { building_name: "Apple Store at 401 West 14th Street" },
  { building_name: "Archstone Clinton at 515 West 52nd Street" },
  { building_name: "Ariel East at 2633 Broadway" },
  { building_name: "Ariel West at 2628 Broadway" },
  { building_name: "Atelier at 635 West 42nd Street" },
  { building_name: "Avalon Riverview North(Queens West)" },
  { building_name: "Avery聽at 100 Riverside Boulevard" },
  { building_name: "Barclay Tower at聽10 Barclay Street" },
  { building_name: "Beacon Tower(DUMBO, Brooklyn)" },
  { building_name: "Blue at 105 Norfolf Street" },
  { building_name: "The Centria at 16 West 48th Street" },
  { building_name: "Chelsea Arts Tower at 545 West 25th Street" },
  { building_name: "Chelsea Landmark at 55 West 25th Street" },
  { building_name: "Court Square Place(Long Island City)" },
  { building_name: "The Epic at 125 West 31st Street" },
  { building_name: "Forte Condominiums(Fort Greene, Brooklyn)" },
  { building_name: "Hudson Blue聽at 423 West Street" },
  { building_name: "J Condo at 100 Jay Street(DUMBO)" },
  { building_name: "The Link 鈥310 West 52nd Street" },
  { building_name: "Lookout Hill at 199 State Street(Brooklyn)" },
  { building_name: "Millennium Tower Residences at 30 West Street" },
  { building_name: "Place 57 at 207 East 57th Street" },
  { building_name: "The Veneto at 250 East 53rd Street" },
  { building_name: "Weill Medical College Ambulatory Care Facility" },
  { building_name: "One Carnegie Hill at 215 East 96th Street" },
  { building_name: "1600 Broadway" },
  { building_name: "255 Hudson Street" },
  { building_name: "33 West End Avenue" },
  { building_name: "Brooklyn Marriott South Tower(Downtown Brooklyn)" },
  { building_name: "Bryant Park Tower at 1330 Avenue of the Americas" },
  { building_name: "The Cielo at 450 East 83rd Street" },
  { building_name: "East Coast tower(Queens West)" },
  { building_name: "Hearst聽Tower聽at 300 West 57th Street" },
  { building_name: "Memorial Sloan - Kettering Zuckerman Research Building" },
  { building_name: "The Morgan Library Museum and Expansion" },
  { building_name: "Orion聽at 350 West 42nd Street" },
  { building_name: "Rockefeller Center Hotel at 25 West 51st Street" },
  { building_name: "Sutton 57 at 212 East 57th Street" },
  { building_name: "The Urban Glass House聽at 330 Spring Street" },
  { building_name: "U.S.District Courthouse(Downtown Brooklyn)" },
  { building_name: "The Verdesian at 211 North End Avenue" },
  { building_name: "Zinc Building at 475 Greenwich Street" },
  { building_name: "Marriott Marquis NYC" },
  { building_name: "Renaissance New York Hotel" },
  { building_name: "W New York Times Square" },
  { building_name: "Edison Hotel" },
  { building_name: "Crowne Plaza Times Square Manhattan" },
  { building_name: "The Time Hotel" },
  { building_name: "Milford Plaza" },
  { building_name: "Paramount Hotel(Hard Rock Hotel New York)" },
  { building_name: "The Muse" },
  { building_name: "Hilton Garden Inn Times Square" },
  { building_name: "Comfort Inn Midtown" },
  { building_name: "Quality Hotel Times Square" },
  { building_name: "Best Western President" },
  { building_name: "Mayfair New York Hotel" },
  { building_name: "Portland Square Hotel" },
  { building_name: "Yotel New York" },
  { building_name: "Westin New York at Times Square Hotel" },
  { building_name: "Hilton Times Square" },
  { building_name: "Millennium Broadway" },
  { building_name: "Casablanca Hotel" },
  { building_name: "Hotel 41 at Times Square" },
  { building_name: "Carter Hotel" },
  { building_name: "Flatotel" },
  { building_name: "Sheraton New York Hotel And Towers" },
  { building_name: "Sheraton Manhattan Hotel" },
  { building_name: "Novotel New York Hotel" },
  { building_name: "Amsterdam Court Hotel" },
  { building_name: "The Michelangelo Hotel" },
  { building_name: "Hampton Inn Times Square North" },
  { building_name: "Washington Jefferson Hotel" },
  { building_name: "Rihga Royal New York, A JW Marriott Hotel" },
  { building_name: "Ameritania Hotel" },
  { building_name: "Wellington Hotel" },
  { building_name: "Da Vinci Hotel" },
  { building_name: "The Moderne" },
  { building_name: "Park Central New York Hotel" },
  { building_name: "Dream" },
  { building_name: "Hilton New York" },
  { building_name: "The Blakely New York(The Gorham)" },
  { building_name: "Belvedere Hotel" },
  { building_name: "414 Inn New York" },
  { building_name: "Skyline Hotel" },
  { building_name: "Mandarin Oriental, New York" },
  { building_name: "Trump International Hotel and Tower" },
  { building_name: "Hudson New York Hotel" },
  { building_name: "The West Park Hotel" },
  { building_name: "Executive Club At West Park" },
  { building_name: "Mayflower On The Park" },
  { building_name: "Holiday Inn Midtown Hotel" },
  { building_name: "Jumeirah Essex House" },
  { building_name: "The Plaza" },
  { building_name: "Le Parker Meridien New York" },
  { building_name: "Park Savoy Hotel" },
  { building_name: "The Helmsley Park Lane" },
  { building_name: "Helmsley Windsor Hotel" },
  { building_name: "The Ritz - Carlton New York, Central Park" },
  { building_name: "Salisbury Hotel" },
  { building_name: "The Plaza Hotel" },
  { building_name: "The Pierre" },
  { building_name: "The Sherry Netherland" },
  { building_name: "The Helmsley Carlton House" },
  { building_name: "Four Seasons New York" },
  { building_name: "The Regency Hotel" },
  { building_name: "The Lowell" },
  { building_name: "The Peninsula New York" },
  { building_name: "Warwick New York" },
  { building_name: "The Shoreham Hotel" },
  { building_name: "The St.Regis, New York" },
  { building_name: "Hotel Elysee" },
  { building_name: "Omni Berkshire Place" },
  { building_name: "Chambers" },
  { building_name: "The Waldorf Astoria" },
  { building_name: "Doubletree Metropolitan Hotel" },
  { building_name: "The Kimberly Hotel" },
  { building_name: "W Hotel New York" },
  { building_name: "Marriott New York Eastside" },
  { building_name: "InterContinental The Barclay New York" },
  { building_name: "Radisson Lexington Hotel New York" },
  { building_name: "Helmsley Middletowne Hotel" },
  { building_name: "Affinia 50" },
  { building_name: "Best Western Hospitality House" },
  { building_name: "San Carlos Hotel" },
  { building_name: "The Benjamin" },
  { building_name: "Pickwick Arms Hotel" },
  { building_name: "The Roger Smith" },
  { building_name: "The Waldorf Towers, A Conrad Hotel" },
  { building_name: "Courtyard by Marriott Midtown East" },
  { building_name: "Oakwood Midtown" },
  { building_name: "Roosevelt Hotel New York" },
  { building_name: "Vanderbilt Ymca" },
  { building_name: "Churchill Residence Suites" },
  { building_name: "Fitzpatrick Grand Central Hotel" },
  { building_name: "New York Helmsley" },
  { building_name: "The New York Palace" },
  { building_name: "Sofitel New York" },
  { building_name: "Iroquois" },
  { building_name: "Library Hotel" },
  { building_name: "Affinia Dumont" },
  { building_name: "Grand Hyatt New York" },
  { building_name: "W New York 鈥The Court" },
  { building_name: "W New York 鈥The Tuscany" },
  { building_name: "Shelburne Murray Hill" },
  { building_name: "Kitano New York Hotel" },
  { building_name: "Bedford Hotel" },
  { building_name: "Eastgate Tower Suite Hotel" },
  { building_name: "70 Park Avenue" },
  { building_name: "Sheraton Russell Hotel" },
  { building_name: "Jolly Madison Towers" },
  { building_name: "Morgans" },
  { building_name: "Murray Hill East Suites" },
  { building_name: "Hotel Pennsylvania" },
  { building_name: "Comfort Inn New York" },
  { building_name: "Travel Inn Hotel" },
  { building_name: "Best Western Convention Center Hotel" },
  { building_name: "Metro Hotel" },
  { building_name: "Maritime Hotel" },
  { building_name: "Arlington Hotel" },
  { building_name: "Washington Square Hotel" },
  { building_name: "W New York 鈥Union Square" },
  { building_name: "Hotel Gansevoort" },
  { building_name: "Tribeca Grand Hotel" },
  { building_name: "Soho Grand Hotel" },
  { building_name: "60 Thompson" },
  { building_name: "Solita Soho Hotel 鈥Clarion Collection" },
  { building_name: "Mercer Hotel" },
  { building_name: "Howard Johnson Express Inn" },
  { building_name: "Sohotel Pioneer of Soho" },
  { building_name: "Off Soho Suites Hotel" },
  { building_name: "Downtown Hotel" },
  { building_name: "The Ritz - Carlton New York Battery Park" },
  { building_name: "Millenium Hilton" },
  { building_name: "New York Marriott Financial Center" },
  { building_name: "Embassy Suites Hotel New York City" },
  { building_name: "Holiday Inn Wall Street District" },
  { building_name: "Club Quarters, Downtown" },
  { building_name: "The Wall Street Inn" },
  { building_name: "Best Western Seaport Inn Downtown" },
  { building_name: "Cosmopolitan Hotel" },
  { building_name: "Bridgestreet 85 John Street" },
  { building_name: "Manhattan Seaport Suites" },
  { building_name: "Comfort Inn Central Park West" },
  { building_name: "West Side YMCA" },
  { building_name: "The Phillips Club" },
  { building_name: "Inn New York City" },
  { building_name: "Hotel Beacon" },
  { building_name: "The Milburn Hotel" },
  { building_name: "Amsterdam Inn" },
  { building_name: "On The Ave Hotel in New York City" },
  { building_name: "Belleclaire Hotel" },
  { building_name: "The Lucerne Hotel" },
  { building_name: "The Hayden Hotel" },
  { building_name: "Excelsior Hotel" },
  { building_name: "Riverside Tower Hotel" },
  { building_name: "Quality Hotel On Broadway" },
  { building_name: "Newton Hotel" },
  { building_name: "West End Studios & Hostel" },
  { building_name: "Broadway Tower" },
  { building_name: "West Side Inn & Hostel" },
  { building_name: "The Melrose Hotel" },
  { building_name: "Lyden Gardens Suite Hotel" },
  { building_name: "Hotel Plaza Athenee" },
  { building_name: "Surrey Suite Hotel" },
  { building_name: "The Carlyle, A Rosewood Hotel" },
  { building_name: "The Mark, New York" },
  { building_name: "The Stanhope Park Hyatt New York" },
  { building_name: "The Franklin Hotel" },
  { building_name: "Hotel Wales" },
  { building_name: "Marriott New York at the Brooklyn Bridge" },
  { building_name: "Best Western Gregory Hotel" },
  { building_name: "Comfort Inn Brooklyn" },
  { building_name: "Golden Gate Inn" },
  { building_name: "Days Inn Brooklyn NY" },
  { building_name: "Red Carpet Inn New York City" },
  { building_name: "Milford Plaza Hotel" },
  { building_name: "Hotel Edison" },
  { building_name: "Gershwin Hotel" },
  { building_name: "Herald Square Hotel" },
  { building_name: "Roger Williams Hotel" },
  { building_name: "Red Roof Inn Manhattan" },
  { building_name: "Inn at Irving Place" },
  { building_name: "Le Parker Meridien" },
  { building_name: "The Regent Wall Street" },
  { building_name: "Algonquin Hotel" },
  { building_name: "Waldorf Astoria" },
  { building_name: "Plaza Hotel" },
  { building_name: "The St.Regis" },
  { building_name: "The Bryant Park" },
  { building_name: "1 New York Plaza" },
  { building_name: "1 Pace Plaza" },
  { building_name: "10 East 40th Street" },
  { building_name: "1095 Avenue of the Americas" },
  { building_name: "4 World Trade Center" },
  { building_name: "11 Times Square" },
  { building_name: "1166" },
  { building_name: "14 Wall Street" },
  { building_name: "1500 Broadway" },
  { building_name: "1501 Broadway" },
  { building_name: "170-176 John Street Building" },
  { building_name: "1740 Broadway" },
  { building_name: "25 Henry, New York, NY 10002" },
  { building_name: "20 Exchange Place-CIBC Building" },
  { building_name: "21 Astor Place" },
  { building_name: "240 Centre Street" },
  { building_name: "245 Park Avenue" },
  { building_name: "25 Henry St, New York, NY 10002, USA" },
  { building_name: "250 West 90th Street" },
  { building_name: "257 Central Park West" },
  { building_name: "299 Park Avenue" },
  { building_name: "299 West 12th Street" },
  { building_name: "3 Park Avenue" },
  { building_name: "3 World Trade Center" },
  { building_name: "300 East 57th Street" },
  { building_name: "New York Times Building" },
  { building_name: "302 West 12th Street" },
  { building_name: "32 Avenue of the Americas" },
  { building_name: "33 Thomas Street" },
  { building_name: "353 Central Park West" },
  { building_name: "359 Broadway" },
  { building_name: "36 East 72nd Street" },
  { building_name: "360 Central Park West" },
  { building_name: "369th Regiment Armory" },
  { building_name: "37 Wall Street" },
  { building_name: "375 Pearl Street" },
  { building_name: "399 Park Avenue" },
  { building_name: "461 Fifth Avenue" },
  { building_name: "535 West End Avenue" },
  { building_name: "555 Edgecombe Avenue" },
  { building_name: "59 West 12th Street" },
  { building_name: "590 Madison Avenue" },
  { building_name: "60 Hudson Street" },
  { building_name: "650 5th Avenue" },
  { building_name: "69th Regiment Armory" },
  { building_name: "750 7th Avenue" },
  { building_name: "810 Fifth Avenue" },
  { building_name: "810 Seventh Avenue" },
  { building_name: "880 Fifth Avenue" },
  { building_name: "888 7th Avenue" },
  { building_name: "907 Fifth Avenue" },
  { building_name: "Americas Tower" },
  { building_name: "919 Third Avenue" },
  { building_name: "99 Church Street" },
  { building_name: "995 Fifth Avenue" },
  { building_name: "A.I.R. Gallery" },
  { building_name: "Aaron Davis Hall" },
  { building_name: "ABC No Rio" },
  { building_name: "Adam Clayton Powell Jr. State Office Building" },
  { building_name: "Admiral's House" },
  { building_name: "Aeolian Hall" },
  { building_name: "Al Hirschfeld Theatre" },
  { building_name: "Albemarle Building" },
  { building_name: "Alexander Hamilton Bridge" },
  { building_name: "Alexander Hamilton U.S. Custom House" },
  { building_name: "Alfred E. Smith House" },
  { building_name: "Allen-Beville House" },
  { building_name: "Allerton Hotel for Women" },
  { building_name: "American Bank Note Company Building" },
  { building_name: "American Museum of Natural History" },
  { building_name: "American Surety Building" },
  { building_name: "NYSE MKT" },
  { building_name: "AMEX" },
  { building_name: "Angel Orensanz Center" },
  { building_name: "Apollo Theater" },
  { building_name: "Appleton Building" },
  { building_name: "Artists space" },
  { building_name: "Audubon Ballroom" },
  { building_name: "Audubon Terrace" },
  { building_name: "Avatar Studios" },
  { building_name: "Avery Fisher Hall" },
  { building_name: "AXA Equitable Center" },
  { building_name: "B'nai Yosef Synagogue" },
  { building_name: "Bank of the Metropolis" },
  { building_name: "Barbizon 63" },
  { building_name: "Baruch College" },
  { building_name: "Battery Park Control House" },
  { building_name: "Bayard-Condict Building" },
  { building_name: "Beacon Theatre, New York" },
  { building_name: "8 Spruce Street" },
  { building_name: "Belaire Apartments" },
  { building_name: "Belmont Hotel" },
  { building_name: "Belvedere Castle" },
  { building_name: "Bennett Building" },
  { building_name: "Beth Hamedrash Hagadol" },
  { building_name: "Bialystoker Synagogue" },
  { building_name: "Billiou-Stillwell-Perine House" },
  { building_name: "Bleecker Street Cinema" },
  { building_name: "Boathouse on the Lullwater of the Lake in Prospect Park" },
  { building_name: "Bohemian National Hall" },
  { building_name: "Bowery Poetry Club" },
  { building_name: "Bradford Hotel" },
  { building_name: "James L. Breese House" },
  { building_name: "Bretton Hall, Manhattan" },
  { building_name: "British Pavilion Interiors" },
  { building_name: "Broad Exchange Building" },
  { building_name: "Church of St. John Nepomucene" },
  { building_name: "Broadway Bridge" },
  { building_name: "Broadway-Chambers Building" },
  { building_name: "Brooklyn Borough Hall" },
  { building_name: "Brooklyn Bridge" },
  { building_name: "Brooklyn Museum" },
  { building_name: "Burlington House" },
  { building_name: "Calyon Building" },
  { building_name: "Canterbury Hall, New York City" },
  { building_name: "Carnegie Hall" },
  { building_name: "Castle Village, Manhattan" },
  { building_name: "Castle Williams" },
  { building_name: "Cathedral of Saint John the Divine" },
  { building_name: "CBS Broadcast Center" },
  { building_name: "Central Synagogue" },
  { building_name: "Cherry Lane Theatre" },
  { building_name: "Christopher Street Pier" },
  { building_name: "Church of Notre Dame" },
  { building_name: "Church of the Ascension, Episcopal" },
  { building_name: "Church of the Sacred Heart of Jesus" },
  { building_name: "Church of the Transfiguration, Roman Catholic" },
  { building_name: "Circle in the Square Theatre" },
  { building_name: "City Hall Post Office and Courthouse" },
  { building_name: "New York City College of Technology" },
  { building_name: "De La Salle Institute" },
  { building_name: "CitySpire Center" },
  { building_name: "Civic Club" },
  { building_name: "Claremont Riding Academy" },
  { building_name: "Claude McKay Residence" },
  { building_name: "Cleburne Building" },
  { building_name: "Colony Club" },
  { building_name: "Con-Ed Redevelopment" },
  { building_name: "Condé Nast Building" },
  { building_name: "Conference House" },
  { building_name: "Congregation Baith Israel Anshei Emes" },
  { building_name: "Congregation Beth Elohim" },
  { building_name: "Congregation Beth Israel West Side Jewish Center" },
  { building_name: "Congregation Chasam Sopher" },
  { building_name: "Congregation Kehilath Jeshurun" },
  { building_name: "Congregation Ohab Zedek" },
  { building_name: "Congregation Shaare Zedek" },
  { building_name: "Congregation Shearith Israel" },
  { building_name: "Continental Bank Building" },
  { building_name: "Cooper Union" },
  { building_name: "Cooperative Village" },
  { building_name: "Cornell Farmhouse" },
  { building_name: "Corning Museum of Glass" },
  { building_name: "Croton Distributing Reservoir" },
  { building_name: "Daniel LeRoy House" },
  { building_name: "David H. Koch Theater" },
  { building_name: "Decker Building" },
  { building_name: "DeVinne Press Building" },
  { building_name: "Dewey Arch" },
  { building_name: "Downtown Community Television Center" },
  { building_name: "DuMont Building" },
  { building_name: "Dunbar Apartments" },
  { building_name: "E. D. Baylies House" },
  { building_name: "E. V. Haughwout Building" },
  { building_name: "Earl Carroll Theatre" },
  { building_name: "East Midwood Jewish Center" },
  { building_name: "East River Tunnels" },
  { building_name: "One World Trade Center" },
  { building_name: "East Side Access" },
  { building_name: "Ed Sullivan Theater" },
  { building_name: "Edgar Allan Poe Cottage" },
  { building_name: "Edith Fabbri House" },
  { building_name: "Eldridge Street Synagogue" },
  { building_name: "Elgin Theater" },
  { building_name: "Elmer Holmes Bobst Library" },
  { building_name: "Equitable Building" },
  { building_name: "Equitable Life Building" },
  { building_name: "Essex Street Market" },
  { building_name: "200 West Street" },
  { building_name: "Eventi" },
  { building_name: "Everard Baths" },
  { building_name: "Everett Building" },
  { building_name: "Federal Hall" },
  { building_name: "Federal Reserve Bank of New York" },
  { building_name: "Federal Reserve Bank of New York Building" },
  { building_name: "Film Center Building" },
  { building_name: "First Houses" },
  { building_name: "First Roumanian-American Congregation" },
  { building_name: "First Shearith Israel Graveyard" },
  { building_name: "Fischbach Gallery" },
  { building_name: "Five World Trade Center" },
  { building_name: "Florence Mills House" },
  { building_name: "Fort Tompkins Quadrangle" },
  { building_name: "Four Seasons Hotel New York" },
  { building_name: "Four World Financial Center" },
  { building_name: "Fraunces Tavern" },
  { building_name: "Fred F. French Building" },
  { building_name: "Fulton Houses" },
  { building_name: "Garibaldi-Meucci Museum" },
  { building_name: "General Electric Building" },
  { building_name: "General Grant National Memorial" },
  { building_name: "General Winfield Scott House" },
  { building_name: "Germania Life Insurance Company Building" },
  { building_name: "Gillender Building" },
  { building_name: "GiraSole" },
  { building_name: "Grace Church" },
  { building_name: "Gramercy Park Hotel" },
  { building_name: "Grand Central Terminal" },
  { building_name: "Grand Hotel" },
  { building_name: "Grant Houses" },
  { building_name: "Grolier Club" },
  { building_name: "Hamilton Fish House" },
  { building_name: "Hamilton Grange National Memorial" },
  { building_name: "Hampshire House" },
  { building_name: "Harlem River Houses" },
  { building_name: "Harper Brothers Building" },
  { building_name: "Harperly Hall" },
  { building_name: "Harry F. Sinclair House" },
  { building_name: "Harvard Club of New York" },
  { building_name: "Hayden Planetarium" },
  { building_name: "Hearst Tower" },
  { building_name: "Hedden Construction Company" },
  { building_name: "Hendrik Hudson Hotel" },
  { building_name: "Hilltop Park" },
  { building_name: "Hiram Charles Todd House" },
  { building_name: "HLW International" },
  { building_name: "Holy Name of Jesus Roman Catholic Church" },
  { building_name: "Holy Rosary Church" },
  { building_name: "Home Insurance Plaza" },
  { building_name: "Hotel Attraction" },
  { building_name: "Hotel Carter" },
  { building_name: "Hotel Chelsea" },
  { building_name: "Hotel Gerard" },
  { building_name: "Hotel Theresa" },
  { building_name: "Hotel Wolcott" },
  { building_name: "Hudson Place" },
  { building_name: "Hudson View Gardens" },
  { building_name: "International House of New York" },
  { building_name: "Iridium Jazz Club" },
  { building_name: "Irish Hunger Memorial" },
  { building_name: "Isaac T. Hopper House" },
  { building_name: "Islamic Cultural Center of New York" },
  { building_name: "Jacob K. Javits Convention Center" },
  { building_name: "Jacob K. Javits Federal Building" },
  { building_name: "James B. Duke House" },
  { building_name: "James Brown House" },
  { building_name: "James F. D. Lanier Residence" },
  { building_name: "James Farley Post Office" },
  { building_name: "James L. Watson Court of International Trade Building" },
  { building_name: "James P. Lanier House" },
  { building_name: "James Watson House" },
  { building_name: "James Weldon Johnson Residence" },
  { building_name: "Jarmulowsky Bank Building" },
  { building_name: "John Bowne House" },
  { building_name: "John Golden Theatre" },
  { building_name: "John Street Methodist Church" },
  { building_name: "Joyce Theater" },
  { building_name: "Kehila Kedosha Janina" },
  { building_name: "Kehilas Yetev Lev D'Satmar" },
  { building_name: "Kent Automatic Garages" },
  { building_name: "Khal Adath Jeshurun" },
  { building_name: "King Manor" },
  { building_name: "Kings County Savings Bank" },
  { building_name: "Kinsley & Darling Druggists" },
  { building_name: "Kips Bay Plazza" },
  { building_name: "Kips Bay Towers" },
  { building_name: "Knickerbocker Club" },
  { building_name: "Kostabi World Trade Center" },
  { building_name: "L.P. Hollander Company Building" },
  { building_name: "Laing Store" },
  { building_name: "Langham Place, New York" },
  { building_name: "Latting Observatory" },
  { building_name: "Lenox Hill Hospital" },
  { building_name: "Lever House" },
  { building_name: "Lincoln Square Synagogue" },
  { building_name: "Metropolitan Life North Building" },
  { building_name: "Lincoln Towers" },
  { building_name: "Litchfield Villa" },
  { building_name: "Little Red Lighthouse" },
  { building_name: "Long Island City Courthouse" },
  { building_name: "Lorillard Snuff Mill" },
  { building_name: "Lotos Club" },
  { building_name: "Louis Armstrong House" },
  { building_name: "Louis Sullivan Building" },
  { building_name: "Ludlow Street Jail" },
  { building_name: "Luxor Hotel (New York City)" },
  { building_name: "Macombs Dam Bridge" },
  { building_name: "Macy's Herald Square" },
  { building_name: "Madison Avenue Bridge" },
  { building_name: "Madison Square Garden" },
  { building_name: "Madison Square Garden Towers" },
  { building_name: "Manhattan Center" },
  { building_name: "Manhattan House of Detention for Men" },
  { building_name: "Manhattan Life Insurance Building" },
  { building_name: "Manhattan Municipal Building" },
  { building_name: "Manhattan New York Temple" },
  { building_name: "Manhattan Plaza" },
  { building_name: "Manhattan Psychiatric Center" },
  { building_name: "Manhattanville Houses" },
  { building_name: "Margaret Sanger Clinic" },
  { building_name: "Marine Air Terminal" },
  { building_name: "Marine Midland Building" },
  { building_name: "Mariner's Temple" },
  { building_name: "Marlton House" },
  { building_name: "Matthew Henson Residence" },
  { building_name: "1221 Avenue of the Americas" },
  { building_name: "Merkin Concert Hall" },
  { building_name: "Meseritz Synagogue" },
  { building_name: "MetLife Building" },
  { building_name: "Metropolitan Fireproof Warehouse" },
  { building_name: "Metropolitan Life Insurance Company Tower" },
  { building_name: "Metropolitan Museum of Art" },
  { building_name: "Metropolitan Opera" },
  { building_name: "Metropolitan Opera House" },
  { building_name: "Metropolitan Savings Bank Building" },
  { building_name: "MigdalOr" },
  { building_name: "Millennium Point" },
  { building_name: "MiMA" },
  { building_name: "Minton's Playhouse" },
  { building_name: "Moondance Diner" },
  { building_name: "Morgan Library" },
  { building_name: "Morris–Jumel Mansion" },
  { building_name: "1 Lincoln Plaza" },
  { building_name: "Morse Building" },
  { building_name: "Morton F. Plant House" },
  { building_name: "Mount Sinai Jewish Center" },
  { building_name: "Mrs. Graham Fair Vanderbilt House" },
  { building_name: "National September 11 Memorial & Museum" },
  { building_name: "NBA Store" },
  { building_name: "One World Financial Center" },
  { building_name: "Neil Simon Theatre" },
  { building_name: "New Dorp Light" },
  { building_name: "New St. Marks Baths" },
  { building_name: "New York Amsterdam News Building" },
  { building_name: "New York Cancer Hospital" },
  { building_name: "69th Street Transfer Bridge" },
  { building_name: "New York City Bar Association" },
  { building_name: "New York City Center" },
  { building_name: "New York City Hall" },
  { building_name: "New York City Police Building" },
  { building_name: "New York Coliseum" },
  { building_name: "New York County Lawyers' Association Building" },
  { building_name: "New York Crystal Palace" },
  { building_name: "New York Hilton Midtown" },
  { building_name: "New York Life Building" },
  { building_name: "New York Public Library" },
  { building_name: "New York Tribune Building" },
  { building_name: "New York Yacht Club" },
  { building_name: "Nuyorican Poets Café" },
  { building_name: "NYSE" },
  { building_name: "O'Neill Building" },
  { building_name: "Olcott Hotel" },
  { building_name: "Old Broadway Synagogue" },
  { building_name: "One Astor Plaza" },
  { building_name: "One Chase Manhattan Plaza" },
  { building_name: "One Court Square" },
  { building_name: "One Liberty Plaza" },
  { building_name: "One Madison" },
  { building_name: "One Times Square" },
  { building_name: "One Worldwide Plaza" },
  { building_name: "One57" },
  { building_name: "Otto H. Kahn House" },
  { building_name: "Park Central Hotel" },
  { building_name: "Park East Synagogue" },
  { building_name: "Park Plaza Apartments" },
  { building_name: "Penn South" },
  { building_name: "Pennsylvania Station" },
  { building_name: "Philippine Center" },
  { building_name: "Philosophy Hall" },
  { building_name: "St. Gabriel's Roman Catholic Church" },
  { building_name: "Pier 54" },
  { building_name: "Pier 63" },
  { building_name: "Plymouth Church" },
  { building_name: "Potter Building" },
  { building_name: "Public School 9" },
  { building_name: "Public Theater" },
  { building_name: "Puck Building" },
  { building_name: "Pure Oil Gas Station" },
  { building_name: "Quaker Meeting-house" },
  { building_name: "Radio City Music Hall" },
  { building_name: "Ramath Orah" },
  { building_name: "Random House Tower" },
  { building_name: "Riverside" },
  { building_name: "Riverside South" },
  { building_name: "Riverton Houses" },
  { building_name: "Robbins & Appleton Building" },
  { building_name: "Robert K. Kraft Field at Lawrence A. Wien Stadium" },
  { building_name: "Rockefeller Center" },
  { building_name: "Royalton Hotel" },
  { building_name: "Saint Malachy's Roman Catholic Church" },
  { building_name: "Samuel J. Friedman Theatre" },
  { building_name: "Samuel J. Tilden House" },
  { building_name: "Sara Delano Roosevelt Memorial House" },
  { building_name: "Schomburg Center for Research in Black Culture" },
  { building_name: "Scribner Building" },
  { building_name: "Seventh Regiment Armory" },
  { building_name: "Seville Hotel" },
  { building_name: "388 Greenwich Street" },
  { building_name: "Silk Centre" },
  { building_name: "Singer Building" },
  { building_name: "Sohmer Piano Building" },
  { building_name: "Solar 1" },
  { building_name: "Solomon R. Guggenheim Museum" },
  { building_name: "Sony Music Studios" },
  { building_name: "South Bushwick Reformed Protestant Dutch Church Complex" },
  { building_name: "South Ferry Plaza" },
  { building_name: "Southbridge Towers" },
  { building_name: "Spuyten Duyvil Bridge" },
  { building_name: "St. Cecilia's Church and Convent" },
  { building_name: "St. Charles Borromeo's Church" },
  { building_name: "St. Charles's Church" },
  { building_name: "St. James Theatre" },
  { building_name: "St. James' Church" },
  { building_name: "St. Jean Baptiste Catholic Church" },
  { building_name: "St. Mark's Church in-the-Bowery" },
  { building_name: "St. Monica's Church" },
  { building_name: "St. Nicholas Greek Orthodox Church" },
  { building_name: "St. Nicholas Houses" },
  { building_name: "St. Patrick's Cathedral" },
  { building_name: "St. Paul Building" },
  { building_name: "St. Paul the Apostle Church" },
  { building_name: "St. Thomas Episcopal Church" },
  { building_name: "Statue of Liberty" },
  { building_name: "Steinway Hall" },
  { building_name: "Strivers' Row" },
  { building_name: "Studebaker Building, Manhattan" },
  { building_name: "Stuyvesant Town—Peter Cooper Village" },
  { building_name: "Television City Tower" },
  { building_name: "Tenth Street Studio Building" },
  { building_name: "The Actors' Temple" },
  { building_name: "The Ansonia" },
  { building_name: "The Apthorp" },
  { building_name: "The Beresford" },
  { building_name: "The Block House" },
  { building_name: "The Century" },
  { building_name: "The Continental NYC" },
  { building_name: "The Corinthian" },
  { building_name: "The Crimson Beech" },
  { building_name: "The Ear Inn" },
  { building_name: "The Eldorado" },
  { building_name: "The Epic" },
  { building_name: "The Forum at 343 East 74th Street" },
  { building_name: "The Grand Madison" },
  { building_name: "The Langham" },
  { building_name: "The Majestic" },
  { building_name: "The New York Times Building" },
  { building_name: "The Octagon" },
  { building_name: "The Orion" },
  { building_name: "The Pennmark" },
  { building_name: "The San Remo" },
  { building_name: "The Sherry-Netherland" },
  { building_name: "The Solaire" },
  { building_name: "The Times Square Building" },
  { building_name: "The Westin New York Grand Central Hotel" },
  { building_name: "The Whitby" },
  { building_name: "The Wilbraham" },
  { building_name: "World Trade Center Tower 5" },
  { building_name: "Theodore Roosevelt Birthplace National Historic Site" },
  { building_name: "Third Avenue Bridge" },
  { building_name: "Three World Financial Center" },
  { building_name: "Tibor de Nagy Gallery" },
  { building_name: "Tiffany and Company Building" },
  { building_name: "Time-Life Building" },
  { building_name: "Tower 49" },
  { building_name: "Tower Verre" },
  { building_name: "Town Hall" },
  { building_name: "TWA Flight Center" },
  { building_name: "Trinity Church" },
  { building_name: "Trinity Church Cemetery" },
  { building_name: "Trump Palace Condominiums" },
  { building_name: "Trump Park Avenue" },
  { building_name: "Tweed Courthouse" },
  { building_name: "Two World Financial Center" },
  { building_name: "Unisphere" },
  { building_name: "United Nations Headquarters" },
  { building_name: "United Nations Secretariat Building" },
  { building_name: "United Palace Theater" },
  { building_name: "United States - Bethel Home" },
  { building_name: "United States Post Office–Cooper Station" },
  { building_name: "University Club" },
  { building_name: "University Club of New York" },
  { building_name: "University Settlement Society of New York" },
  { building_name: "University Village" },
  { building_name: "US Post Office-Saratoga Springs" },
  { building_name: "Valentine-Varian House" },
  { building_name: "Verizon Building" },
  { building_name: "Villard Houses" },
  { building_name: "Vivian Beaumont Theater" },
  { building_name: "Voorlezer's House" },
  { building_name: "W. R. Grace Building" },
  { building_name: "Waldorf Astoria New York" },
  { building_name: "Warwick New York Hotel" },
  { building_name: "Washington Bridge" },
  { building_name: "Washington Square Village" },
  { building_name: "Wave Hill" },
  { building_name: "Webster Hotel" },
  { building_name: "Western Union Telegraph Building" },
  { building_name: "Weylin Hotel" },
  { building_name: "Whitehall Building" },
  { building_name: "Will Marion Cook House" },
  { building_name: "Williamsburg Bridge" },
  { building_name: "Williamsburgh Savings Bank" },
  { building_name: "Williamsburgh Savings Bank Tower" },
  { building_name: "Willis Avenue Bridge" },
  { building_name: "Winter Garden Atrium" },
  { building_name: "World Financial Center" },
  { building_name: "WTC Towers Memorial" },
  { building_name: "Wyckoff-Bennett Homestead" },
  { building_name: "Yale Club of New York City" },
  { building_name: "Zeckendorf Tower" },
];
export default function Building({
  params: { selected, setSelected },
}: {
  params: {
    selected: DataType;
    setSelected: Dispatch<SetStateAction<DataType>>;
  };
}) {
  const handleSelect = (val: SingleValue<DataType>) => {
    setSelected(val || { building_name: "Willow Heights Apartments" });
  };

  //Add your search logic here.
  const customFilter = (option: DataType, searchText: string) => {
    if (option.building_name.toLowerCase().includes(searchText.toLowerCase())) {
      return true;
    } else {
      return false;
    }
  };
  return (
    <div>
      <span>Building Name</span>
      <Select
        className="react-selectcomponent"
        classNamePrefix="name-select"
        onChange={handleSelect}
        getOptionLabel={(option) => `${option.building_name}`}
        getOptionValue={(option) => `${option}`}
        isOptionSelected={(option) =>
          selected.building_name === option.building_name ? true : false
        }
        options={sampleData}
        isSearchable={true}
        // filterOption={customFilter}
        // onInputChange={handleInputChange}
        noOptionsMessage={() => null}
        placeholder={"Enter Name"}
        autoFocus={true}
        // menuIsOpen={menuOpen}
      />
    </div>
  );
}
